export enum ENotificationType {
  UNKNOWN = "UNKNOWN",
  COURSE_PURCHASE = "COURSE_PURCHASE",
  MEMBERSHIP_PURCHASE = "MEMBERSHIP_PURCHASE",
  MEMBERSHIP_WILL_EXPIRE = "MEMBERSHIP_WILL_EXPIRE",
  MEMBERSHIP_IS_EXPIRED = "MEMBERSHIP_IS_EXPIRED"
}