export const NOTIFICATION_TYPE_UNKNOWN = "UNKNOWN";
export const NOTIFICATION_TYPE_COURSE_PURCHASE = "COURSE_PURCHASE";
export const NOTIFICATION_TYPE_MEMBERSHIP_PURCHASE = "MEMBERSHIP_PURCHASE";
export const NOTIFICATION_TYPE_MEMBERSHIP_IS_EXPIRED = "MEMBERSHIP_IS_EXPIRED";
export const NOTIFICATION_TYPE_MEMBERSHIP_WILL_EXPIRE =
  "MEMBERSHIP_WILL_EXPIRE";

export const SSE_TYPE_ADD_BELL_NOTIFICATION = "ADD_BELL_NOTIFICATION";
export const SSE_TYPE_REMOVE_BELL_NOTIFICATION = "REMOVE_BELL_NOTIFICATION";
export const SSE_TYPE_ADD_TOASTER_NOTIFICATION = "ADD_TOASTER_NOTIFICATION";

export const CAST_TYPE_EVERYONE = "EVERYONE";
export const CAST_TYPE_ADMINS = "ADMINS";
export const CAST_TYPE_USER = "USER";

export const NOTIFICATION_SEVERITY_SUCCESS = "SUCCESS";
export const NOTIFICATION_SEVERITY_WARNING = "WARNING";
export const NOTIFICATION_SEVERITY_ERROR = "ERROR";
export const NOTIFICATION_SEVERITY_INFO = "INFO";
