name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm ci --production
          npm run build
          tar -czf ../frontend.tar.gz -C build .

      # Build Backend
      - name: Build Backend
        run: |
          cd backend
          npm ci --production
          npm run build
          tar -czf ../backend.tar.gz -C dist package.json package-lock.json node_modules .

      # Deploy Frontend to VPS
      - name: Upload Frontend Archive
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.FRONTEND_USER }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          source: "frontend.tar.gz"
          target:  ${{ secrets.FRONTEND_TARGET }}

      - name: Extract Frontend Archive
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.FRONTEND_USER }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          script: |
            cd "${{ secrets.FRONTEND_TARGET }}"
            tar -xzf frontend.tar.gz
            rm frontend.tar.gz
            echo "Frontend deployed successfully."

      # Deploy Backend to VPS
      - name: Upload Backend Archive
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          source: "backend.tar.gz"
          target: ${{ secrets.BACKEND_TARGET }}

      - name: Extract Backend Archive and Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            cd "${{ secrets.BACKEND_TARGET }}"
            tar -xzf backend.tar.gz
            rm backend.tar.gz
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
            . ~/.bashrc
            npm install pm2 -g
            pm2 restart main
            echo "Backend deployed and restarted successfully."
